#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLE: Notes on Artin-Whaples
#+SUBTITLE: 
#+DATE: <2016-09-16 Fri>
#+AUTHOR: Soham Chowdhury
#+EMAIL: chow.soham@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.50.1 (Org mode 8.3.5)

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: 
#+LATEX_HEADER_EXTRA: \input{/home/mrkgnao/math/preamble.tex}
#+DESCRIPTION:
#+KEYWORDS:

* Main theorem
If a field satisfies the valuation product formula, and if one of those valuations is of a suitable type, then it is forced to be either a number field or a function field.

* Valuations
** TODO Prime divisor = "equivalence class of valuations"
** Lemmas
- If $|\cdot|_1$ and $|\cdot|_2$ are two inequivalent valuations, there is some $\gamma$ such that \[|\gamma|_1 < 1 \text{ and } |\gamma|_2 > 1.\]
- If $|\cdot|_i$ are inequivalent, there is some $\alpha$ such that \[|\alpha|_1 > 1\text{ and }|\alpha|_{i>1} < 1.\]
- If $|\cdot|_i$ are inequivalent, for every $\epsilon>0$, there is an $\alpha$ such that \[|\alpha-1|_1 \leq 1 \text{ and } |\alpha|_{\nu>1}\leq 1.\]
** Approximation theorem
Given pairs $(|\cdot|_i, \alpha_i)$, with the $|\cdot|_i$ inequivalent, then for every $\epsilon>0$ there is some $\alpha$ with 
\[|\alpha - \alpha_i|_i < \epsilon.\]
** Corollary
If $|\cdot|_i$ are nontrivial and inequivalent, then any identity of the form
\[\prod |\alpha|_{i}^{\nu_i} = 1\]
with $0\neq \alpha\in k$ implies that the $\nu_i$ are all $0$.
This "precludes the possibility that a finite number of valuations can ever be interrelated", to paraphrase the original, but maybe an infinite number of valuations is okay?
* The product formula 
** Axiom 1
There is a set $M$ of pairs $(\pp, |\cdot|_\pp)$ such that, for any $0\neq \alpha \in k$,
- $\val\alpha\pp = 1$ for almost all $\pp$
- Extending the product over all primes, 
  \[ \prod_\pp \val\alpha\pp = 1 \]
For instance, for $6\in\Q$, the product looks like
\[ \val6{(0)} \cdot\val6{(2)}\cdot\val6{(3)} = 6\cdot 2^{-1} \cdot 3^{-1} = 1 \]
** Idèles
We associate to $M$ a space of vectors $v={ (v_\pp) }_\pp$, where $v_\pp \in k_\pp$. We will write $\val v\pp$ for $\val{v_\pp}\pp$.
*** Definition
A vector of this form is an idele if 
- $v_\pp\neq 0$ for all $\pp$
- $v_\pp = 1$ for almost all $\pp$
*** Embedding
There is a natural embedding $k\hookrightarrow V(k)$ reminiscent of the "diagonal embedding": writing $i_\pp$ for the inclusion $k\to k_\pp$,
\[\alpha\mapsto{ (i_\pp(\alpha)) }_\pp\]
*** "Volume"
For each idele $\fka$, define
\[V(\fka) = \prod_\pp \val\fka\pp \]
**** For elements coming from $k$ via the embedding, notice that we have $V(\alpha) = 1$. This gives
\[V(\alpha\fka) = V(\fka)\]
**** A map $\pp\mapsto x_\pp \in\R$, with $x_\pp = 1$ for almost all $\pp$, gives a set of vectors $\val c\pp \leq \val\fka\pp$ which we call the parallelotope with dimensions $x$.
*** Order
(+*I don't get this yet. Arbitrary integer ... what?*+ Wait, now I do.)

The order of a set of elements is defined as follows:
**** If $k$ has an archimedean valuation, then order is the number of elements.
**** If not, there is some field of constants $k_0\subset k$. The order of a set is then defined to be $q^s$, where we define $q$ and $s$ as follows:
***** If $k_0$ is finite, $q$ is its number of elements. Otherwise, $q$ is an arbitrary fixed number greater than $1$. 
$s$ is the number of elements in the set that are linearly independent over $k_0$.
*** The \(M\)-function
The order of a set of elements contained in the parallelotope of size $\fka$ will be denoted $M(\fka)$.
Note that, for nonzero $\theta\in k$, $M(\theta\fka)=M(\fka)$ since multiplying by $\theta$ changes the parallelotope of size $\fka$ into the parallelotope of size $\theta\fka$ and does not change the order.
*** The ring of \(\pp\)-integers
The set of elements $\alpha\in k$ for which $\val\alpha\pp \leq 1$ forms a ring, which we denote $\op$.
The subset of $\op$ with $\val\alpha\pp < 1$ forms an ideal in this ring, which, by abuse of notation, is also denoted $\pp$. Now we have a quotient field $\op/\pp$, and so on. The /order/ of this field is called the norm $N\pp$ of $\pp$. For instance, if there is a constant field $k_0\subseteq k^{\pp} = \op/\pp$, we have
\[ N\pp = {(\# k_0)}^{[k^\pp : k_0]} \]
** Axiom 2
The set $M$ of [[Axiom 1]] contains at least one prime $\qq$, which is either
- discrete, with a finite quotient field of finite order $N\qq$
- archimedean, with $k_\qq=\R$ or $\C$
** Another valuation
For $\alpha\neq 0$, define a valuation as follows:
- For $\pp \not | \infty$ set
  \[ { ||\alpha|| }_\pp = \frac1{ N\pp^\nu } \]
  where $\nu = \ord_\pp(\alpha)$.
- If $k=\R$, $||\cdot||_\pp$ is defined to be the standard absolute value.
- If $k=\C$, $||\cdot||_\pp$ is set to be the squared absolute value.
** Theorem 2
We can construct $M$ such that both [[Axiom 1]] and [[Axiom 2]] hold for the following fields:
- a number field, i.e., a finite extension $K/\Q$
- a field of algebraic functions over any field $k_1$ (that is, a finite extension $K/k_1(z)$ with $z$ transcendental $/k_1$)
*** Lemma 4
*** Lemma 5
*** Lemma 6

* Characterizing fields by the valuation product formula
** (Main) theorem 3
If a field satisfies [[Axiom 1]] and [[Axiom 2]], it is of one of the two types in [[Theorem 2]]. Furthermore, [[Axiom 2]] is satisfied for every place $\pp$.

* Parallelotopes
** Theorem 4 
There are positive $C, D$ such that for all ideles $\fka$ we have
\[ CV(\fka) < M(\fka) \leq \max(1, DV(\fka)) \]

** Definitions
Let $U$ be the multiplicative group of "absolute units", that is, $x\in k$ is in $U$ if ${||x||}_\pp = 1$ for all $\pp$.
- If there is a constant field $k_0$, $U=\ut {k_0}$.
- "In case order means number of elements, $U$ must be a finite group since it is contained in the parallelotope of size $1$, so $U$ consists of all roots of unity in $k$.
Now select a finite set $S$ of primes that contains all the archimedean primes. By $\fka_S$ we mean the ideles $\fka$ such that $\vval{ \fka } = 1$ for all $\pp\not\in S$. As one might expect, $e_\pp\in k$ which belong to $\fka_S$ are called \(S\)-units.
